export const Attributes = {
  Responses: [
    "id",
    "SequenceNumber",
    "Type",
    "Priority",
    "HandlingResource",
    "Zone",
    "AgencyName",
    "DispatchGroup",
    "IncidentNumber",
    "PrimaryResponse",
    "CreationDate",
    "ClassificationName",
    "DispatcherDisplayName",
    "DispatcherLogonName",
    "CreationTime",
    "StatusTime",
    "IncidentCreationTime",
    "ResponseLocation",
    "RespAlarmLevel",
    "PrimaryResource",
    "MilestoneName",
    "OriginName",
    "PersonCount",
    "Status",
    "ImportDateTime",
    "ResponseTypeCategory",
  ],

  ProcessTimes: ["CreationTime", "Dispatch", "Disposition", "Completion"],

  ResourcesAssigned: [
    "AgencyName",
    "IsPrimaryUnit",
    "ResourceName",
    "ResourceDescription",
    "StationName",
    "XCoordinate",
    "YCoordinate",
    "AssignOdometerOut",
    "AssignOdometerOut",
  ],

  Call: [
    "CallerName",
    "PhoneNumber",
    "PhoneNumberExt",
    "FreeFormatAddress",
    "ESN",
    "Near",
    "Age",
    "IsPhoneOwner",
    "Gender",
    "SIN",
  ],
  Comment: [
    "TimeStamp1",
    "Info",
    "AgentName",
    "AgentDisplayName",
    "Workstation",
    "CommentTypeOID",
  ],
};
